kind: Service
apiVersion: v1
metadata:
  name: turbo-umbrella
  labels:
    app: turbo-umbrella
spec:
  type: ClusterIP
  selector:
    app: turbo-umbrella
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: turbo-umbrella
spec:
  replicas: 1
  selector:
    matchLabels:
      app: turbo-umbrella
  template:
    metadata:
      labels:
        app: turbo-umbrella
        version: v1
    spec:
      containers:
      - name: turbo-umbrella
        image: turbo-umbrella
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
